"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-11
"""
from alembic import op
import sqlalchemy as sa


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("businesses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("phone", sa.String(64)), sa.Column("address", sa.Text()), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("working_hours", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("channels", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("channel_type", sa.String(32), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("external_id", sa.String(255)), sa.Column("token_ref", sa.String(255)), sa.Column("webhook_secret", sa.String(255)), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.String(64)))
    op.create_table("contacts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("full_name", sa.String(255)), sa.Column("phone", sa.String(64)), sa.Column("email", sa.String(255)), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("doctor_capabilities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("capability_key", sa.String(128), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("is_available", sa.Boolean(), nullable=False), sa.Column("answer_template", sa.Text()), sa.Column("fallback_text", sa.Text()))
    op.create_table("business_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("rule_key", sa.String(128), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_table("prompt_configs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("system_prompt", sa.Text(), nullable=False), sa.Column("tone", sa.String(255)), sa.Column("forbidden_topics", sa.JSON()), sa.Column("escalation_rules", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("doctor_users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("telegram_user_id", sa.BigInteger(), nullable=False), sa.Column("full_name", sa.String(255)), sa.Column("role", sa.String(64), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.String(64)))
    op.create_table("services", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("category", sa.String(128)), sa.Column("description", sa.Text()), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("requires_doctor_confirmation", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("animal_types", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("name", sa.String(128), nullable=False), sa.Column("is_supported", sa.Boolean(), nullable=False), sa.Column("comment", sa.Text()))
    op.create_table("prices", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("service_id", sa.Integer(), sa.ForeignKey("services.id"), nullable=False), sa.Column("price_from", sa.Numeric(10, 2)), sa.Column("price_to", sa.Numeric(10, 2)), sa.Column("currency", sa.String(8), nullable=False), sa.Column("comment", sa.Text()), sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_table("service_animal_types", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("service_id", sa.Integer(), sa.ForeignKey("services.id"), nullable=False), sa.Column("animal_type_id", sa.Integer(), sa.ForeignKey("animal_types.id"), nullable=False), sa.Column("is_available", sa.Boolean(), nullable=False), sa.Column("comment", sa.Text()))
    op.create_table("contact_channel_accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id"), nullable=False), sa.Column("channel_id", sa.Integer(), sa.ForeignKey("channels.id"), nullable=False), sa.Column("external_user_id", sa.String(255), nullable=False), sa.Column("external_chat_id", sa.String(255)), sa.Column("username", sa.String(255)), sa.Column("display_name", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True)))
    op.create_table("animals", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id"), nullable=False), sa.Column("name", sa.String(255)), sa.Column("animal_type", sa.String(128)), sa.Column("breed", sa.String(255)), sa.Column("age", sa.String(128)), sa.Column("sex", sa.String(64)), sa.Column("is_neutered", sa.Boolean()), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("conversations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id"), nullable=False), sa.Column("channel_id", sa.Integer(), sa.ForeignKey("channels.id"), nullable=False), sa.Column("status", sa.String(64), nullable=False), sa.Column("current_intent", sa.String(64)), sa.Column("last_message_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("messages", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("conversations.id"), nullable=False), sa.Column("sender_type", sa.String(32), nullable=False), sa.Column("text", sa.Text(), nullable=False), sa.Column("raw_payload", sa.JSON()), sa.Column("llm_context", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True)))
    op.create_table("intake_forms", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id"), nullable=False), sa.Column("animal_id", sa.Integer(), sa.ForeignKey("animals.id")), sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("conversations.id"), nullable=False), sa.Column("client_name", sa.String(255)), sa.Column("phone", sa.String(64)), sa.Column("animal_type", sa.String(128)), sa.Column("animal_name", sa.String(255)), sa.Column("breed", sa.String(255)), sa.Column("age", sa.String(128)), sa.Column("sex", sa.String(64)), sa.Column("complaint", sa.Text()), sa.Column("symptoms_started_at_text", sa.Text()), sa.Column("urgency", sa.String(32), nullable=False), sa.Column("preferred_callback_time", sa.String(255)), sa.Column("source_channel", sa.String(32), nullable=False), sa.Column("status", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("leads", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id"), nullable=False), sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("conversations.id"), nullable=False), sa.Column("intake_form_id", sa.Integer(), sa.ForeignKey("intake_forms.id")), sa.Column("source_channel", sa.String(32), nullable=False), sa.Column("interest", sa.Text()), sa.Column("status", sa.String(64), nullable=False), sa.Column("priority", sa.String(32), nullable=False), sa.Column("assigned_to", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("appointments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id"), nullable=False), sa.Column("animal_id", sa.Integer(), sa.ForeignKey("animals.id")), sa.Column("lead_id", sa.Integer(), sa.ForeignKey("leads.id")), sa.Column("service_id", sa.Integer(), sa.ForeignKey("services.id")), sa.Column("appointment_date", sa.Date()), sa.Column("appointment_time", sa.Time()), sa.Column("status", sa.String(64), nullable=False), sa.Column("comment", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("handoff_tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("conversations.id"), nullable=False), sa.Column("lead_id", sa.Integer(), sa.ForeignKey("leads.id")), sa.Column("reason", sa.Text(), nullable=False), sa.Column("priority", sa.String(32), nullable=False), sa.Column("status", sa.String(64), nullable=False), sa.Column("assigned_to", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("vet_store_products", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("category", sa.String(128)), sa.Column("description", sa.Text()), sa.Column("price", sa.Numeric(10, 2)), sa.Column("is_available", sa.Boolean(), nullable=False))
    op.create_table("knowledge_sources", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("type", sa.String(64), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("content", sa.Text()), sa.Column("file_url", sa.Text()), sa.Column("status", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("knowledge_chunks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("source_id", sa.Integer(), sa.ForeignKey("knowledge_sources.id")), sa.Column("content", sa.Text(), nullable=False), sa.Column("metadata", sa.JSON()), sa.Column("embedding", sa.JSON()), sa.Column("created_at", sa.String(64)))
    op.create_table("analytics_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id")), sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("conversations.id")), sa.Column("lead_id", sa.Integer(), sa.ForeignKey("leads.id")), sa.Column("channel", sa.String(32)), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("event_payload", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True)))
    op.create_table("report_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("report_type", sa.String(32), nullable=False), sa.Column("period_start", sa.DateTime(timezone=True), nullable=False), sa.Column("period_end", sa.DateTime(timezone=True), nullable=False), sa.Column("data_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)))
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("business_id", sa.Integer(), sa.ForeignKey("businesses.id"), nullable=False), sa.Column("action", sa.String(128), nullable=False), sa.Column("payload", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True)))


def downgrade() -> None:
    for table in [
        "audit_logs", "report_snapshots", "analytics_events", "knowledge_chunks", "knowledge_sources",
        "vet_store_products", "handoff_tasks", "appointments", "leads", "intake_forms", "messages",
        "conversations", "animals", "contact_channel_accounts", "service_animal_types", "prices",
        "animal_types", "services", "doctor_users", "prompt_configs", "business_rules",
        "doctor_capabilities", "contacts", "channels", "businesses",
    ]:
        op.drop_table(table)
